apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: security-lab
  labels:
    app: secure-demo
spec:
  containers:
  - name: secure-container
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  automountServiceAccountToken: false